//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWENCompletion
    {
        public string CompletionType { get; set; }
        public string OtherElective { get; set; }
        public string CompletionCourse { get; set; }
        public string Credits { get; set; }
        public string OtherElectiveCrdites { get; set; }
        public string CoreClassCredits { get; set; }
        public string TotalCredits { get; set; }
    }
}
